#!/bin/sh

REACT_APP_STACKS_BLOCKCHAIN_API_URL=$STACKS_BLOCKCHAIN_API_URL \
REACT_APP_MINING_MONITOR_GRAPHQL=$MINING_MONITOR_GRAPHQL \
REACT_APP_IPFS_GATEWAY_URL=$IPFS_GATEWAY_URL \
REACT_APP_MEMPOOL_SPACE_URL=$MEMPOOL_SPACE_URL \
npx react-inject-env set

serve -s build -n